version: '3.7'
services:
  app:
    image: ${DOCKER_REGISTRY}/selectel-hc
    container_name: selectel-hc
    environment:
      SELECTEL_API_TOKEN: ${SELECTEL_API_TOKEN}
      SELECTEL_API_URL: ${SELECTEL_API_URL}
      SELECTEL_EMAIL_CLIENT: ${SELECTEL_EMAIL_CLIENT}
    ports:
      - ${EXTERNAL_PORT}:80
    networks:
      shc_net:

networks:
  shc_net:
    name: shc_net
