version: '3.7'
services:
  app:
    image: ${/php7-tools:latest
    container_name: selectel-hc-dev
    command: php artisan serve --host=0.0.0.0 --port=80
    environment:
      XDEBUG_CONFIG: remote_host=127.0.0.1
      SELECTEL_API_TOKEN: ${SELECTEL_API_TOKEN}
      SELECTEL_API_URL: ${SELECTEL_API_URL}
      APP_ENV: development
    volumes:
      - ./app/:/var/www
    ports:
      - ${EXTERNAL_PORT}:80
    networks:
      shc_net:

networks:
  shc_net:
    name: shc_net
